###
# Check for the root response

GET http://localhost:8080
Accept: application/text

###
# Download markets.zip file

GET http://localhost:8080/api/bulk-download/s3?dataset=markets&variant=null&market=null
Authorization: api-key 1234567890
Accept: application/zip

###
# Check for the options

OPTIONS http://localhost:8080
Accept: application/text

###
