# ╔═════════════════════════════════════════════════════════════════════════════════════════════════
# ║     configuration.dart
# ╠═════════════════════════════════════════════════════════════════════════════════════════════════
# ║     Created: 07.03.2025
# ║
# ║     Copyright (c) 2025 James Dooley <james@dooley.ch>
# ║
# ║     History:
# ║     07.03.2025: Initial version
# ╚═════════════════════════════════════════════════════════════════════════════════════════════════

version = "1.0.1"

[server]
port = 8080
files = "/Users/jdooley/Development/mock-api/files"

[api]
key = "1234567890"
max-calls = 60

