name: mock_api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.1

# Add regular dependencies here.
dependencies:
  toml: ^0.16.0
  path: ^1.9.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0

executables:
  mock_api:
